#!/usr/bin/env bash
# runtime.sh - Generate .env files for local development

do_local() {
  local project="$1"
  local env="$2"

  local resolved
  resolved=$(resolve_vars "$project" "$env")

  if [[ -z "$resolved" ]]; then
    echo -e "${RED}Error: No variables resolved for $project/$env${NC}"
    exit 1
  fi

  local var_count
  var_count=$(echo "$resolved" | wc -l | xargs)

  if [[ "$DRY_RUN" == "true" ]]; then
    echo -e "${CYAN}=== DRY RUN: $project/$env ($var_count vars) ===${NC}"
    echo "$resolved" | while IFS='=' read -r key value; do
      [[ -z "$key" ]] && continue
      # Mask secrets (show first 4 and last 4 chars)
      if [[ ${#value} -gt 12 ]]; then
        local masked="${value:0:4}...${value: -4}"
        printf "  %-40s=%s\n" "$key" "$masked"
      else
        printf "  %-40s=%s\n" "$key" "$value"
      fi
    done
    return
  fi

  # Determine output path
  local output_path="$OUTPUT"
  if [[ -z "$output_path" ]]; then
    # Default: write to project's .env.local in expected location
    echo -e "${YELLOW}No --output specified. Printing to stdout.${NC}"
    echo -e "${CYAN}# $project/$env - $var_count variables${NC}"
    echo "$resolved"
    return
  fi

  # Write to file
  local output_dir
  output_dir=$(dirname "$output_path")
  mkdir -p "$output_dir"

  {
    echo "# Generated by sync-env on $(date -u +%Y-%m-%dT%H:%M:%SZ)"
    echo "# Project: $project | Environment: $env"
    echo "# DO NOT EDIT - regenerate with: sync-env local -p $project -e $env -o $output_path"
    echo ""
    echo "$resolved"
  } > "$output_path"

  echo -e "${GREEN}Wrote $var_count vars to $output_path${NC}"
}
