#!/usr/bin/env bash
# worktree.sh - Generate .env files for a worktree
#
# Resolves the dev environment for a project and writes .env files
# to the appropriate locations within a worktree directory.

do_worktree() {
  local project="$1"
  local worktree_dir="${OUTPUT:-.}"

  # Use dev environment by default for worktrees
  local env="${ENV:-dev}"

  local resolved
  resolved=$(resolve_vars "$project" "$env")

  if [[ -z "$resolved" ]]; then
    echo -e "${RED}Error: No variables resolved for $project/$env${NC}"
    exit 1
  fi

  local var_count
  var_count=$(echo "$resolved" | wc -l | xargs)

  if [[ "$DRY_RUN" == "true" ]]; then
    echo -e "${CYAN}=== DRY RUN: worktree env for $project/$env ===${NC}"
    echo "  Target dir: $worktree_dir"
    echo "  Variables: $var_count"
    echo ""
    echo "$resolved" | while IFS='=' read -r key value; do
      [[ -z "$key" ]] && continue
      if [[ ${#value} -gt 12 ]]; then
        printf "  %-40s=%s...%s\n" "$key" "${value:0:4}" "${value: -4}"
      else
        printf "  %-40s=%s\n" "$key" "$value"
      fi
    done
    return
  fi

  # Determine env file locations based on project
  local env_paths=()
  case "$project" in
    faabzi)
      env_paths=(
        "clients/faabzi/client/.env.local"
        "clients/faabzi/control-panel/.env.local"
      )
      ;;
    work-macha)
      env_paths=(
        "clients/work-macha/.env.local"
      )
      ;;
    qwickresume)
      env_paths=(
        ".env.local"
      )
      ;;
    *)
      env_paths=(
        ".env.local"
      )
      ;;
  esac

  local header="# Generated by sync-env worktree on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# Project: $project | Environment: $env
# Regenerate: sync-env worktree -p $project -e $env -o $worktree_dir
"

  for env_path in "${env_paths[@]}"; do
    local full_path="$worktree_dir/$env_path"
    local dir
    dir=$(dirname "$full_path")
    mkdir -p "$dir"

    {
      echo "$header"
      echo "$resolved"
    } > "$full_path"

    echo -e "  ${GREEN}Wrote:${NC} $env_path ($var_count vars)"
  done
}
